export const appActionTypes = {
    SET_STATE: 'SET_STATE'
};

export const editorActionTypes = {
    EDITOR_CONTENT_CHANGE: 'EDITOR_CONTENT_CHANGE',
    EDITOR_SET_STATE: 'EDITOR_SET_STATE',
    EDITOR_IMAGE_INSERT: 'EDITOR_IMAGE_INSERT',
    EDITOR_PASTE_CONTENT: 'EDITOR_PASTE_CONTENT'
};

export const galleryActionTypes = {
    UPDATE_GALLERY_IMAGE_LIST: 'UPDATE_GALLERY_IMAGE_LIST',
    DRAG_STARTED: 'DRAG_STARTED',
    DRAG_END: 'DRAG_END'
};
