export const appActionTypes = {
    SET_STATE: 'SET_STATE'
};

export const editorActionTypes = {
    EDITOR_CONTENT_CHANGE: 'EDITOR_CONTENT_CHANGE',
    EDITOR_SET_STATE: 'EDITOR_SET_STATE',
    EDITOR_IMAGE_INSERT: 'EDITOR_IMAGE_INSERT',
    EDITOR_PASTE_CONTENT: 'EDITOR_PASTE_CONTENT'
};

export const galleryActionTypes = {
    FETCHED_PHOTOS: 'FETCHED_PHOTOS',
    FETCH_SAMPLE_PHOTOS: 'FETCH_SAMPLE_PHOTOS',
    DRAG_STARTED: 'DRAG_STARTED',
    DRAG_END: 'DRAG_END'
};
